# -*- coding: utf-8 -*-
"""Creación chat llm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QFtRh4IDNpqK2SMhc9jzRVu1j8gxstCr

## Los roles de los mensajes para construir un chat son:

- system: Define el comportamiento general del asistente.
- user: Contiene el mensaje o la pregunta del usuario.
- assistant: Contiene la respuesta generada por el modelo.

Vamos a utilizar esto para construir un chat finalmente.
"""

from openai import OpenAI
OPENAI_API_KEY = "tu-API-KEY-aquí"
client = OpenAI(
    api_key=OPENAI_API_KEY,
)

MODEL_CHAT = "gpt-4"
MODEL_SUMMARY = "gpt-4"

SYSTEM_PROMPT = {
    "role": "system",
    "content": (
        "Eres un experto en creación de modelos LLM, uso de APIs de diferentes modelos, "
        "experto en programación eficiente y machine learning."
    )
}

resumen_memoria = ""

historial = []
max_tokens = 8000

def construir_mensajes_para_api(resumen: str, historial_reciente: list) -> list:
    mensajes = [SYSTEM_PROMPT]

    if resumen.strip():
        mensajes.append({
            "role": "system",
            "content": f"Memoria resumida de la conversación anterior:\n{resumen}"
        })

    mensajes.extend(historial_reciente)
    historial_reciente
    return mensajes

def crear_mensaje_resumen(resumen_actual: str, mensajes_a_resumir: list) -> str:
    prompt_resumen = [
        {
            "role": "system",
            "content": (
                "Resume la conversación de forma compacta y útil para continuar después. "
                "No inventes información. Conserva objetivos, decisiones, restricciones, "
                "datos importantes y temas abiertos. Devuelve solo el resumen final."
            )
        },
        {
            "role": "user",
            "content": (
                f"Resumen previo:\n{resumen_actual}\n\n"
                f"Mensajes a resumir:\n{mensajes_a_resumir}"
            )
        }
    ]

    respuesta = client.chat.completions.create(
        model=MODEL_SUMMARY,
        messages=prompt_resumen
    )

    return respuesta.choices[0].message.content

q = ""
while q.lower().strip() != "salir":
    q = input("Pregunta: ").strip()

    if not q:
        continue

    if q.lower() == "salir":
        break

    historial.append({"role": "user", "content": q})

    # Si el historial crece demasiado, resumimos los mensajes antiguos
    if response.usage.total_tokens > max_tokens:
        # Conservamos los últimos mensajes más recientes
        parte_antigua = historial[:-12]
        historial = historial[-12:]

        # Convertimos la parte antigua en un resumen acumulado
        resumen_memoria = crear_mensaje_resumen(resumen_memoria, parte_antigua)

    mensajes_api = construir_mensajes_para_api(resumen_memoria, historial)

    try:
        response = client.chat.completions.create(
            model=MODEL_CHAT,
            messages=mensajes_api
        )

        resp = response.choices[0].message.content
        historial.append({"role": "assistant", "content": resp})

        print("\nRespuesta:", resp)
        print("=" * 80)
        print("Mensajes en historial:", len(historial))
        print("Tokens usados en la última llamada:", response.usage.total_tokens)
        print("=" * 80)

    except Exception as e:
        print(f"Error al consultar el modelo: {e}")

historial

resumen_memoria